import { useQuery } from '@tanstack/react-query'
import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'

// Generated by @hey-api/openapi-ts with the @tanstack/react-query plugin
// (`pnpm gen`). If the symbol/path differs in your output, adjust this import —
// the plugin names it `<operationId>Options`.
import { searchMoviesOptions } from '../client/@tanstack/react-query.gen'
import { useDebouncedValue } from '../hooks/useDebouncedValue'

export const Route = createFileRoute('/')({
  component: Home,
})

function Home() {
  const [term, setTerm] = useState('')
  const debounced = useDebouncedValue(term.trim(), 200)

  const { data, isFetching } = useQuery({
    ...searchMoviesOptions({ query: { q: debounced, limit: 20 } }),
    // Only search once there's something to search for.
    enabled: debounced.length > 0,
  })

  const results = data ?? []
  const showEmpty = debounced.length > 0 && !isFetching && results.length === 0

  return (
    <main className="container">
      <h1>My Movies</h1>

      <input
        className="search-input"
        type="search"
        value={term}
        onChange={(event) => setTerm(event.target.value)}
        placeholder="Search your collection…"
        // eslint-disable-next-line jsx-a11y/no-autofocus
        autoFocus
      />

      {isFetching && <p className="muted">Searching…</p>}
      {showEmpty && <p className="muted">No matches.</p>}

      <ul className="results">
        {results.map((result) => (
          <li key={result.movie.id}>
            <strong>{result.movie.title}</strong> ({result.movie.releaseYear})
            {result.locatedReleases.length === 0 ? (
              <span className="muted"> — not shelved yet</span>
            ) : (
              <ul>
                {result.locatedReleases.map((located) => (
                  <li key={located.release.id}>
                    {located.location.bookcase.name} · shelf {located.location.shelf.position} ·
                    slot {located.location.placement.position}
                  </li>
                ))}
              </ul>
            )}
          </li>
        ))}
      </ul>
    </main>
  )
}
