version: 2

enable-beta-ecosystems: true

registries:
  docker-hardened:
    type: docker-registry
    url: dhi.io
    username: ${{ secrets.DHI_USERNAME }}
    password: ${{ secrets.DHI_TOKEN }}

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - docker-hardened
  - package-ecosystem: "docker"
    directories:
      - "/"
      - "frontend"
    schedule:
      interval: "daily"
    registries:
      - docker-hardened
  - package-ecosystem: "npm"
    directory: "frontend"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
