Main:
  files:
  - $all
  - "!$test"
  allow:
  - $gostd
  - github.com/jackc/pgx/v5
  deny:
    reflect: Please don't use reflect package
Test:
  files:
  - $test
  allow:
  - $gostd
  - github.com/jackc/pgx/v5
  - github.com/testcontainers/testcontainers-go
  - github.com/testcontainers/testcontainers-go/modules/postgres
  deny:
    reflect: Please don't use reflect package
    github.com/stretchr/testify: Please don't use testify package
