services:
  db:
    image: dhi.io/postgres:18-alpine3.22-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mymovies
    volumes:
      - db_data:/var/lib/postgresql/18/docker:rw
    ports:
      - 5432:5432

volumes:
  db_data:
