// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: locations.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createBookcase = `-- name: CreateBookcase :one

INSERT INTO bookcases (name, position)
VALUES ($1, $2)
RETURNING id, name, position, created_at
`

type CreateBookcaseParams struct {
	Name     string
	Position int32
}

// Bookcases -----------------------------------------------------------------
func (q *Queries) CreateBookcase(ctx context.Context, arg CreateBookcaseParams) (Bookcase, error) {
	row := q.db.QueryRow(ctx, createBookcase, arg.Name, arg.Position)
	var i Bookcase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createShelf = `-- name: CreateShelf :one

INSERT INTO shelves (bookcase_id, position)
VALUES ($1, $2)
RETURNING id, bookcase_id, position, created_at
`

type CreateShelfParams struct {
	BookcaseID uuid.UUID
	Position   int32
}

// Shelves -------------------------------------------------------------------
func (q *Queries) CreateShelf(ctx context.Context, arg CreateShelfParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, createShelf, arg.BookcaseID, arg.Position)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.BookcaseID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBookcase = `-- name: DeleteBookcase :exec
DELETE FROM bookcases
WHERE id = $1
`

func (q *Queries) DeleteBookcase(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBookcase, id)
	return err
}

const deleteShelf = `-- name: DeleteShelf :exec
DELETE FROM shelves
WHERE id = $1
`

func (q *Queries) DeleteShelf(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShelf, id)
	return err
}

const getBookcase = `-- name: GetBookcase :one
SELECT id, name, position, created_at FROM bookcases
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBookcase(ctx context.Context, id uuid.UUID) (Bookcase, error) {
	row := q.db.QueryRow(ctx, getBookcase, id)
	var i Bookcase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getShelf = `-- name: GetShelf :one
SELECT id, bookcase_id, position, created_at FROM shelves
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetShelf(ctx context.Context, id uuid.UUID) (Shelf, error) {
	row := q.db.QueryRow(ctx, getShelf, id)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.BookcaseID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listBookcases = `-- name: ListBookcases :many
SELECT id, name, position, created_at FROM bookcases
ORDER BY position, created_at
`

func (q *Queries) ListBookcases(ctx context.Context) ([]Bookcase, error) {
	rows, err := q.db.Query(ctx, listBookcases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Bookcase
	for rows.Next() {
		var i Bookcase
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlacementsByShelf = `-- name: ListPlacementsByShelf :many
SELECT
    p.id, p.release_id, p.shelf_id, p.position, p.created_at,
    r.id, r.movie_id, r.studio, r.country_code, r.upc, r.ean, r.asin, r.release_date, r.casing, r.slipcover, r.blu_ray_discs, r.dvd_discs, r.digital_copy, r.created_at, r.watched, r.comment, r.retailer, r.price, r.price_comment,
    m.id, m.title, m.release_year, m.runtime_min
FROM placements p
JOIN home_video_releases r ON r.id = p.release_id
JOIN movies m ON m.id = r.movie_id
WHERE p.shelf_id = $1
ORDER BY p.position, p.created_at
`

type ListPlacementsByShelfRow struct {
	Placement        Placement
	HomeVideoRelease HomeVideoRelease
	Movie            Movie
}

// Everything physically placed on a shelf, joined to its release and that
// release's movie, in slot order. The feed for rendering a shelf's spines.
func (q *Queries) ListPlacementsByShelf(ctx context.Context, shelfID uuid.UUID) ([]ListPlacementsByShelfRow, error) {
	rows, err := q.db.Query(ctx, listPlacementsByShelf, shelfID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlacementsByShelfRow
	for rows.Next() {
		var i ListPlacementsByShelfRow
		if err := rows.Scan(
			&i.Placement.ID,
			&i.Placement.ReleaseID,
			&i.Placement.ShelfID,
			&i.Placement.Position,
			&i.Placement.CreatedAt,
			&i.HomeVideoRelease.ID,
			&i.HomeVideoRelease.MovieID,
			&i.HomeVideoRelease.Studio,
			&i.HomeVideoRelease.CountryCode,
			&i.HomeVideoRelease.Upc,
			&i.HomeVideoRelease.Ean,
			&i.HomeVideoRelease.Asin,
			&i.HomeVideoRelease.ReleaseDate,
			&i.HomeVideoRelease.Casing,
			&i.HomeVideoRelease.Slipcover,
			&i.HomeVideoRelease.BluRayDiscs,
			&i.HomeVideoRelease.DvdDiscs,
			&i.HomeVideoRelease.DigitalCopy,
			&i.HomeVideoRelease.CreatedAt,
			&i.HomeVideoRelease.Watched,
			&i.HomeVideoRelease.Comment,
			&i.HomeVideoRelease.Retailer,
			&i.HomeVideoRelease.Price,
			&i.HomeVideoRelease.PriceComment,
			&i.Movie.ID,
			&i.Movie.Title,
			&i.Movie.ReleaseYear,
			&i.Movie.RuntimeMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShelvesByBookcase = `-- name: ListShelvesByBookcase :many
SELECT id, bookcase_id, position, created_at FROM shelves
WHERE bookcase_id = $1
ORDER BY position, created_at
`

func (q *Queries) ListShelvesByBookcase(ctx context.Context, bookcaseID uuid.UUID) ([]Shelf, error) {
	rows, err := q.db.Query(ctx, listShelvesByBookcase, bookcaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Shelf
	for rows.Next() {
		var i Shelf
		if err := rows.Scan(
			&i.ID,
			&i.BookcaseID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const locateRelease = `-- name: LocateRelease :one
SELECT
    b.id, b.name, b.position, b.created_at,
    s.id, s.bookcase_id, s.position, s.created_at,
    p.id, p.release_id, p.shelf_id, p.position, p.created_at
FROM placements p
JOIN shelves s ON s.id = p.shelf_id
JOIN bookcases b ON b.id = s.bookcase_id
WHERE p.release_id = $1
`

type LocateReleaseRow struct {
	Bookcase  Bookcase
	Shelf     Shelf
	Placement Placement
}

func (q *Queries) LocateRelease(ctx context.Context, releaseID uuid.UUID) (LocateReleaseRow, error) {
	row := q.db.QueryRow(ctx, locateRelease, releaseID)
	var i LocateReleaseRow
	err := row.Scan(
		&i.Bookcase.ID,
		&i.Bookcase.Name,
		&i.Bookcase.Position,
		&i.Bookcase.CreatedAt,
		&i.Shelf.ID,
		&i.Shelf.BookcaseID,
		&i.Shelf.Position,
		&i.Shelf.CreatedAt,
		&i.Placement.ID,
		&i.Placement.ReleaseID,
		&i.Placement.ShelfID,
		&i.Placement.Position,
		&i.Placement.CreatedAt,
	)
	return i, err
}

const placeRelease = `-- name: PlaceRelease :one

INSERT INTO placements (release_id, shelf_id, position)
VALUES ($1, $2, $3)
ON CONFLICT (release_id)
DO UPDATE SET shelf_id = EXCLUDED.shelf_id, position = EXCLUDED.position
RETURNING id, release_id, shelf_id, position, created_at
`

type PlaceReleaseParams struct {
	ReleaseID uuid.UUID
	ShelfID   uuid.UUID
	Position  int32
}

// Placements ----------------------------------------------------------------
func (q *Queries) PlaceRelease(ctx context.Context, arg PlaceReleaseParams) (Placement, error) {
	row := q.db.QueryRow(ctx, placeRelease, arg.ReleaseID, arg.ShelfID, arg.Position)
	var i Placement
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.ShelfID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const removePlacement = `-- name: RemovePlacement :exec
DELETE FROM placements
WHERE release_id = $1
`

func (q *Queries) RemovePlacement(ctx context.Context, releaseID uuid.UUID) error {
	_, err := q.db.Exec(ctx, removePlacement, releaseID)
	return err
}

const updateBookcase = `-- name: UpdateBookcase :one
UPDATE bookcases
SET name = $2, position = $3
WHERE id = $1
RETURNING id, name, position, created_at
`

type UpdateBookcaseParams struct {
	ID       uuid.UUID
	Name     string
	Position int32
}

func (q *Queries) UpdateBookcase(ctx context.Context, arg UpdateBookcaseParams) (Bookcase, error) {
	row := q.db.QueryRow(ctx, updateBookcase, arg.ID, arg.Name, arg.Position)
	var i Bookcase
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateShelf = `-- name: UpdateShelf :one
UPDATE shelves
SET position = $2
WHERE id = $1
RETURNING id, bookcase_id, position, created_at
`

type UpdateShelfParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateShelf(ctx context.Context, arg UpdateShelfParams) (Shelf, error) {
	row := q.db.QueryRow(ctx, updateShelf, arg.ID, arg.Position)
	var i Shelf
	err := row.Scan(
		&i.ID,
		&i.BookcaseID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
