// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

type HomeVideoRelease struct {
	ID           uuid.UUID
	MovieID      uuid.UUID
	Studio       *string
	CountryCode  *string
	Upc          *string
	Ean          *string
	Asin         *string
	ReleaseDate  *time.Time
	Casing       *string
	Slipcover    *bool
	BluRayDiscs  *int32
	DvdDiscs     *int32
	DigitalCopy  bool
	CreatedAt    time.Time
	Watched      bool
	Comment      *string
	Retailer     *string
	Price        *decimal.Decimal
	PriceComment *string
}

type Movie struct {
	ID          uuid.UUID
	Title       string
	ReleaseYear int32
	RuntimeMin  *int32
}
