// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type HomeVideoRelease struct {
	ID           pgtype.UUID
	MovieID      pgtype.UUID
	Studio       pgtype.Text
	CountryCode  pgtype.Text
	Upc          interface{}
	Ean          interface{}
	Asin         pgtype.Text
	ReleaseDate  pgtype.Date
	Casing       pgtype.Text
	Slipcover    pgtype.Bool
	BluRayDiscs  pgtype.Int4
	DvdDiscs     pgtype.Int4
	DigitalCopy  bool
	CreatedAt    pgtype.Timestamptz
	Watched      bool
	Comment      pgtype.Text
	Retailer     pgtype.Text
	Price        pgtype.Numeric
	PriceComment pgtype.Text
}

type Movie struct {
	ID          pgtype.UUID
	Title       string
	ReleaseYear int32
	RuntimeMin  pgtype.Int4
}
