// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMovie = `-- name: CreateMovie :one
INSERT INTO movies (
  title, release_year, runtime_min
) VALUES (
  $1, $2, $3
)
RETURNING id, title, release_year, runtime_min
`

type CreateMovieParams struct {
	Title       string
	ReleaseYear int32
	RuntimeMin  pgtype.Int4
}

func (q *Queries) CreateMovie(ctx context.Context, arg CreateMovieParams) (Movie, error) {
	row := q.db.QueryRow(ctx, createMovie, arg.Title, arg.ReleaseYear, arg.RuntimeMin)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ReleaseYear,
		&i.RuntimeMin,
	)
	return i, err
}

const deleteMovie = `-- name: DeleteMovie :exec
DELETE FROM movies
WHERE id = $1
`

func (q *Queries) DeleteMovie(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMovie, id)
	return err
}

const getMovie = `-- name: GetMovie :one
SELECT id, title, release_year, runtime_min FROM movies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMovie(ctx context.Context, id pgtype.UUID) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovie, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ReleaseYear,
		&i.RuntimeMin,
	)
	return i, err
}

const listMovies = `-- name: ListMovies :many
SELECT id, title, release_year, runtime_min FROM movies
ORDER BY title
`

func (q *Queries) ListMovies(ctx context.Context) ([]Movie, error) {
	rows, err := q.db.Query(ctx, listMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.RuntimeMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMovie = `-- name: UpdateMovie :exec
UPDATE movies
  SET title = $2,
  release_year = $3,
  runtime_min = $4
WHERE id = $1
`

type UpdateMovieParams struct {
	ID          pgtype.UUID
	Title       string
	ReleaseYear int32
	RuntimeMin  pgtype.Int4
}

func (q *Queries) UpdateMovie(ctx context.Context, arg UpdateMovieParams) error {
	_, err := q.db.Exec(ctx, updateMovie,
		arg.ID,
		arg.Title,
		arg.ReleaseYear,
		arg.RuntimeMin,
	)
	return err
}
