// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const createHomeVideoRelease = `-- name: CreateHomeVideoRelease :one
INSERT INTO home_video_releases (
    movie_id,
    studio,
    country_code,
    upc,
    ean,
    asin,
    release_date,
    casing,
    slipcover,
    blu_ray_discs,
    dvd_discs,
    digital_copy,
    watched,
    comment,
    retailer,
    price,
    price_comment
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, movie_id, studio, country_code, upc, ean, asin, release_date, casing, slipcover, blu_ray_discs, dvd_discs, digital_copy, created_at, watched, comment, retailer, price, price_comment
`

type CreateHomeVideoReleaseParams struct {
	MovieID      uuid.UUID
	Studio       *string
	CountryCode  *string
	Upc          *string
	Ean          *string
	Asin         *string
	ReleaseDate  *time.Time
	Casing       *string
	Slipcover    *bool
	BluRayDiscs  *int32
	DvdDiscs     *int32
	DigitalCopy  bool
	Watched      bool
	Comment      *string
	Retailer     *string
	Price        *decimal.Decimal
	PriceComment *string
}

func (q *Queries) CreateHomeVideoRelease(ctx context.Context, arg CreateHomeVideoReleaseParams) (HomeVideoRelease, error) {
	row := q.db.QueryRow(ctx, createHomeVideoRelease,
		arg.MovieID,
		arg.Studio,
		arg.CountryCode,
		arg.Upc,
		arg.Ean,
		arg.Asin,
		arg.ReleaseDate,
		arg.Casing,
		arg.Slipcover,
		arg.BluRayDiscs,
		arg.DvdDiscs,
		arg.DigitalCopy,
		arg.Watched,
		arg.Comment,
		arg.Retailer,
		arg.Price,
		arg.PriceComment,
	)
	var i HomeVideoRelease
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Studio,
		&i.CountryCode,
		&i.Upc,
		&i.Ean,
		&i.Asin,
		&i.ReleaseDate,
		&i.Casing,
		&i.Slipcover,
		&i.BluRayDiscs,
		&i.DvdDiscs,
		&i.DigitalCopy,
		&i.CreatedAt,
		&i.Watched,
		&i.Comment,
		&i.Retailer,
		&i.Price,
		&i.PriceComment,
	)
	return i, err
}

const deleteHomeVideoRelease = `-- name: DeleteHomeVideoRelease :exec
DELETE FROM home_video_releases
WHERE id = $1
`

func (q *Queries) DeleteHomeVideoRelease(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHomeVideoRelease, id)
	return err
}

const getHomeVideoRelease = `-- name: GetHomeVideoRelease :one
SELECT id, movie_id, studio, country_code, upc, ean, asin, release_date, casing, slipcover, blu_ray_discs, dvd_discs, digital_copy, created_at, watched, comment, retailer, price, price_comment FROM home_video_releases
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetHomeVideoRelease(ctx context.Context, id uuid.UUID) (HomeVideoRelease, error) {
	row := q.db.QueryRow(ctx, getHomeVideoRelease, id)
	var i HomeVideoRelease
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Studio,
		&i.CountryCode,
		&i.Upc,
		&i.Ean,
		&i.Asin,
		&i.ReleaseDate,
		&i.Casing,
		&i.Slipcover,
		&i.BluRayDiscs,
		&i.DvdDiscs,
		&i.DigitalCopy,
		&i.CreatedAt,
		&i.Watched,
		&i.Comment,
		&i.Retailer,
		&i.Price,
		&i.PriceComment,
	)
	return i, err
}

const listHomeVideoReleasesByMovie = `-- name: ListHomeVideoReleasesByMovie :many
SELECT id, movie_id, studio, country_code, upc, ean, asin, release_date, casing, slipcover, blu_ray_discs, dvd_discs, digital_copy, created_at, watched, comment, retailer, price, price_comment FROM home_video_releases
WHERE movie_id = $1
ORDER BY created_at
`

func (q *Queries) ListHomeVideoReleasesByMovie(ctx context.Context, movieID uuid.UUID) ([]HomeVideoRelease, error) {
	rows, err := q.db.Query(ctx, listHomeVideoReleasesByMovie, movieID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []HomeVideoRelease
	for rows.Next() {
		var i HomeVideoRelease
		if err := rows.Scan(
			&i.ID,
			&i.MovieID,
			&i.Studio,
			&i.CountryCode,
			&i.Upc,
			&i.Ean,
			&i.Asin,
			&i.ReleaseDate,
			&i.Casing,
			&i.Slipcover,
			&i.BluRayDiscs,
			&i.DvdDiscs,
			&i.DigitalCopy,
			&i.CreatedAt,
			&i.Watched,
			&i.Comment,
			&i.Retailer,
			&i.Price,
			&i.PriceComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHomeVideoRelease = `-- name: UpdateHomeVideoRelease :one
UPDATE home_video_releases
SET
    studio = $2,
    country_code = $3,
    upc = $4,
    ean = $5,
    asin = $6,
    release_date = $7,
    casing = $8,
    slipcover = $9,
    blu_ray_discs = $10,
    dvd_discs = $11,
    digital_copy = $12,
    watched = $13,
    comment = $14,
    retailer = $15,
    price = $16,
    price_comment = $17
WHERE id = $1
RETURNING id, movie_id, studio, country_code, upc, ean, asin, release_date, casing, slipcover, blu_ray_discs, dvd_discs, digital_copy, created_at, watched, comment, retailer, price, price_comment
`

type UpdateHomeVideoReleaseParams struct {
	ID           uuid.UUID
	Studio       *string
	CountryCode  *string
	Upc          *string
	Ean          *string
	Asin         *string
	ReleaseDate  *time.Time
	Casing       *string
	Slipcover    *bool
	BluRayDiscs  *int32
	DvdDiscs     *int32
	DigitalCopy  bool
	Watched      bool
	Comment      *string
	Retailer     *string
	Price        *decimal.Decimal
	PriceComment *string
}

func (q *Queries) UpdateHomeVideoRelease(ctx context.Context, arg UpdateHomeVideoReleaseParams) (HomeVideoRelease, error) {
	row := q.db.QueryRow(ctx, updateHomeVideoRelease,
		arg.ID,
		arg.Studio,
		arg.CountryCode,
		arg.Upc,
		arg.Ean,
		arg.Asin,
		arg.ReleaseDate,
		arg.Casing,
		arg.Slipcover,
		arg.BluRayDiscs,
		arg.DvdDiscs,
		arg.DigitalCopy,
		arg.Watched,
		arg.Comment,
		arg.Retailer,
		arg.Price,
		arg.PriceComment,
	)
	var i HomeVideoRelease
	err := row.Scan(
		&i.ID,
		&i.MovieID,
		&i.Studio,
		&i.CountryCode,
		&i.Upc,
		&i.Ean,
		&i.Asin,
		&i.ReleaseDate,
		&i.Casing,
		&i.Slipcover,
		&i.BluRayDiscs,
		&i.DvdDiscs,
		&i.DigitalCopy,
		&i.CreatedAt,
		&i.Watched,
		&i.Comment,
		&i.Retailer,
		&i.Price,
		&i.PriceComment,
	)
	return i, err
}
