// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listLocatedReleasesByMovies = `-- name: ListLocatedReleasesByMovies :many
SELECT
    r.id, r.movie_id, r.studio, r.country_code, r.upc, r.ean, r.asin, r.release_date, r.casing, r.slipcover, r.blu_ray_discs, r.dvd_discs, r.digital_copy, r.created_at, r.watched, r.comment, r.retailer, r.price, r.price_comment,
    b.id, b.name, b.position, b.created_at,
    s.id, s.bookcase_id, s.position, s.created_at,
    p.id, p.release_id, p.shelf_id, p.position, p.created_at
FROM home_video_releases r
JOIN placements p ON p.release_id = r.id
JOIN shelves s ON s.id = p.shelf_id
JOIN bookcases b ON b.id = s.bookcase_id
WHERE r.movie_id = ANY($1::uuid[])
ORDER BY b.position, s.position, p.position
`

type ListLocatedReleasesByMoviesRow struct {
	HomeVideoRelease HomeVideoRelease
	Bookcase         Bookcase
	Shelf            Shelf
	Placement        Placement
}

// For the given movies, every release that is physically placed, joined to its
// bookcase/shelf/placement. Unplaced releases are omitted (no location).
func (q *Queries) ListLocatedReleasesByMovies(ctx context.Context, movieIds []uuid.UUID) ([]ListLocatedReleasesByMoviesRow, error) {
	rows, err := q.db.Query(ctx, listLocatedReleasesByMovies, movieIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocatedReleasesByMoviesRow
	for rows.Next() {
		var i ListLocatedReleasesByMoviesRow
		if err := rows.Scan(
			&i.HomeVideoRelease.ID,
			&i.HomeVideoRelease.MovieID,
			&i.HomeVideoRelease.Studio,
			&i.HomeVideoRelease.CountryCode,
			&i.HomeVideoRelease.Upc,
			&i.HomeVideoRelease.Ean,
			&i.HomeVideoRelease.Asin,
			&i.HomeVideoRelease.ReleaseDate,
			&i.HomeVideoRelease.Casing,
			&i.HomeVideoRelease.Slipcover,
			&i.HomeVideoRelease.BluRayDiscs,
			&i.HomeVideoRelease.DvdDiscs,
			&i.HomeVideoRelease.DigitalCopy,
			&i.HomeVideoRelease.CreatedAt,
			&i.HomeVideoRelease.Watched,
			&i.HomeVideoRelease.Comment,
			&i.HomeVideoRelease.Retailer,
			&i.HomeVideoRelease.Price,
			&i.HomeVideoRelease.PriceComment,
			&i.Bookcase.ID,
			&i.Bookcase.Name,
			&i.Bookcase.Position,
			&i.Bookcase.CreatedAt,
			&i.Shelf.ID,
			&i.Shelf.BookcaseID,
			&i.Shelf.Position,
			&i.Shelf.CreatedAt,
			&i.Placement.ID,
			&i.Placement.ReleaseID,
			&i.Placement.ShelfID,
			&i.Placement.Position,
			&i.Placement.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMovies = `-- name: SearchMovies :many
SELECT id, title, release_year, runtime_min FROM movies
WHERE title ILIKE '%' || $1::text || '%'
   OR title % $1::text
ORDER BY similarity(title, $1::text) DESC, title
LIMIT $2::int
`

type SearchMoviesParams struct {
	Query       string
	ResultLimit int32
}

// Case-insensitive fuzzy title search: substring match (ILIKE) OR trigram
// similarity (typo tolerance), ranked by similarity. Backed by the GIN trigram
// index on movies.title.
func (q *Queries) SearchMovies(ctx context.Context, arg SearchMoviesParams) ([]Movie, error) {
	rows, err := q.db.Query(ctx, searchMovies, arg.Query, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Movie
	for rows.Next() {
		var i Movie
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ReleaseYear,
			&i.RuntimeMin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
