import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
// Generated by @hey-api/openapi-ts (`pnpm gen`). If the import path differs in
// Your generated output, point this at the file that exports `client`.
import { client } from './client/client.gen'
// Generated by the TanStack Router plugin on first `vite dev`/`build`.
import { routeTree } from './routeTree.gen'

// Global styles (side-effect import).
import './index.css'

// Dev: Vite proxies /api → the Go backend, so relative URLs avoid CORS.
client.setConfig({ baseUrl: '/api' })

const queryClient = new QueryClient()
const router = createRouter({ routeTree })

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

const rootElement = document.getElementById('root')
if (!rootElement) {
  throw new Error('root element not found')
}

createRoot(rootElement).render(
  <StrictMode>
    <QueryClientProvider client={queryClient}>
      <RouterProvider router={router} />
    </QueryClientProvider>
  </StrictMode>,
)
